[project]
name = "process-template"
version = "0.1.0"
description = "Pulls all 'organizations' from KMD Nexus and populates a Value List in XFlow"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "automation-server-client",
    "kmd-nexus-client",
    "odk-tools",
    "xflow-client",
]

[tool.uv.sources]
automation-server-client = { git = "https://github.com/odense-rpa/automation-server-client.git" }
kmd-nexus-client = { git = "https://github.com/odense-rpa/nexus-client.git", branch = "main" }
odk-tools = { git = "https://github.com/odense-rpa/odk-tools.git", branch = "master" }
xflow-client = { git = "https://github.com/odense-rpa/xflow-client.git", branch = "master" }
